-- ============================================================
-- Temporal Conflict Resolution — Oracle DB Schema
-- (Bonus scope: persistent state storage via cx_Oracle.
--  Table/column shapes mirror schema.sql exactly; only the
--  dialect changes -- SQLite AUTOINCREMENT/datetime('now') become
--  Oracle IDENTITY columns and SYSTIMESTAMP.)
-- ============================================================

CREATE TABLE transaction_state (
    id                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id          VARCHAR2(128) NOT NULL UNIQUE,
    version                 NUMBER DEFAULT 1 NOT NULL,
    source                  VARCHAR2(64) NOT NULL,
    event_timestamp         VARCHAR2(64) NOT NULL,
    amount                  NUMBER,
    currency                VARCHAR2(8),
    status                  VARCHAR2(32),
    reconciliation_notes    VARCHAR2(2000),
    confidence_score        NUMBER,
    event_sequence          NUMBER,
    updated_at              TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE event_log (
    id                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_hash              VARCHAR2(64) NOT NULL UNIQUE,
    transaction_id          VARCHAR2(128) NOT NULL,
    source                  VARCHAR2(64) NOT NULL,
    event_timestamp         VARCHAR2(64) NOT NULL,
    amount                  NUMBER,
    currency                VARCHAR2(8),
    status                  VARCHAR2(32),
    reconciliation_notes    VARCHAR2(2000),
    confidence_score        NUMBER,
    event_sequence          NUMBER,
    is_duplicate            NUMBER(1) DEFAULT 0 NOT NULL,
    processed_at            TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE conflict_log (
    id                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id          VARCHAR2(128) NOT NULL,
    conflict_field          VARCHAR2(32) NOT NULL,
    existing_value          VARCHAR2(2000),
    incoming_value          VARCHAR2(2000),
    existing_source         VARCHAR2(64),
    incoming_source         VARCHAR2(64),
    resolution_source       VARCHAR2(64) NOT NULL,
    resolution_reason       VARCHAR2(2000) NOT NULL,
    resolved_at             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE version_history (
    id                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id          VARCHAR2(128) NOT NULL,
    version                 NUMBER NOT NULL,
    source                  VARCHAR2(64) NOT NULL,
    event_timestamp         VARCHAR2(64) NOT NULL,
    fields_changed          VARCHAR2(2000) NOT NULL,
    snapshot                CLOB NOT NULL,
    created_at              TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE audit_trail (
    id                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id          VARCHAR2(128) NOT NULL,
    action                  VARCHAR2(32) NOT NULL,
    details                 CLOB NOT NULL,
    created_at              TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_event_log_txn      ON event_log(transaction_id);
CREATE INDEX idx_conflict_log_txn   ON conflict_log(transaction_id);
CREATE INDEX idx_version_history_txn ON version_history(transaction_id);
CREATE INDEX idx_audit_trail_txn    ON audit_trail(transaction_id);
